# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'gvmarket' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gvmarket
pod 'Firebase/Core'

pod 'Firebase/Firestore'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'Firebase/Storage'


  target 'gvmarketTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gvmarket-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gvmarket-tvOS

  target 'gvmarket-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
