export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const EMAIL_FIELD_CHANGED = 'EMAIL_FIELD_CHANGED';
export const PASSWORD_FIELD_CHANGED = 'PASSWORD_FIELD_CHANGED';
